#' @title Get Valid Modalities
#' @description Returns a vector of possible output modalities for the supported model.
#' These modalities represent different types of gene expression data that can be
#' generated by the Synthesize Bio API. Note only version 2 can be accessed with this
#' version of the package. If you would like to use v1 models return to 1.x.x versions of this package.
#'
#' @return A character vector containing the valid modality strings.
#' @examples
#' # Get all supported modalities
#' modalities <- get_valid_modalities()
#' print(modalities)
#'
#' # Check if a specific modality is supported
#' "bulk" %in% get_valid_modalities()
#' @export
get_valid_modalities <- function() {
  unlist(MODEL_MODALITIES$"v2.0")
}

#' @title Get Valid Modes
#' @description Returns a vector of possible modes for the supported model.
#' These modes represent different types of gene expression data that can be
#' generated by the Synthesize Bio API.
#'
#' @return A character vector containing the valid mode strings.
#' @examples
#' # Get all supported modes
#' modes <- get_valid_modes()
#' print(modes)
#'
#' # Check if a specific mode is supported
#' "sample generation" %in% get_valid_modes()
#' @export
get_valid_modes <- function() {
  return(c("sample generation", "mean estimation", "metadata prediction"))
}


#' @title Get Valid Query Example
#' @description Generates a sample query for prediction and validation for the v2.0 model.
#' This function provides an example query structure that can be modified for specific needs.
#' The sample query contains two example inputs: one for a cell line with CRISPR perturbation
#' and another for a primary tissue sample with disease information.
#' @param type Specify for what mode you'd like a valid query. Valid options are the same as
#' modes, "sample_generation" and "metadata_prediction"
#' @return A list representing a valid query structure for v2.0.
#' @examples
#' # Get a sample query
#' query <- get_valid_query()
#'
#' # Modify the query for a different modality
#' query$modality <- "bulk"
#'
#' # Adjust the number of samples to generate
#' query$inputs[[1]]$num_samples <- 10
#'
#' # Get a valid query for metadata prediction
#' query <- get_valid_query("metadata_prediction")
#' @export
get_valid_query <- function(type = "sample_generation") {

  stopifnot(type %in% c("sample_generation", "metadata_prediction"))

  sample_generation <- list(
    modality = "bulk",
    mode = "sample generation",
    return_classifier_probs = TRUE,
    seed = 11,
    inputs = list(
      list(
        metadata = list(
          cell_line_ontology_id = "CVCL_0023",
          perturbation_ontology_id = "ENSG00000156127",
          perturbation_type = "crispr",
          perturbation_time = "96 hours",
          sample_type = "cell line"
        ),
        num_samples = 5
      ),
      list(
        metadata = list(
          disease_ontology_id = "MONDO:0011719",
          age_years = "65",
          sex = "female",
          sample_type = "primary tissue",
          tissue_ontology_id = "UBERON:0000945"
        ),
        num_samples = 5
      )
    )
  )

  metadata_prediction <- list(
    modality = "bulk",
    mode = "predict metadata",
    seed = 11,
    inputs = list(
      list(
        classifier_probs = list(
          sex = list(female = 0.9, male = 0.1)
        ),
        latents = list(
          biological = c(0.1, 0.1, 0.3 ),
          perturbation = c(0.2, 0.4, 0.1),
          technical = c(0.3, 0.2, 0.1)
        ),
        metadata = list(sex = "female")
      )
    ),
    model_version = 2.0
  )

  query <-
    switch(type,
           metadata_prediction = metadata_prediction,
           sample_generation = sample_generation
           )

  return(query)
}

#' @title Validate Query Structure
#' @description Validates the structure and contents of the query based on the v2.0 model.
#' This function checks that the query is a list and contains all required keys.
#'
#' @param query A list containing the query data.
#' @return Invisibly returns TRUE if validation passes.
#' Throws an error If the query structure is invalid or missing required keys.
#' @examples
#' # Create a valid query
#' query <- get_valid_query()
#' validate_query(query) # Passes validation
#'
#' # Example with invalid query (missing required key)
#' \dontrun{
#' invalid_query <- list(inputs = list(), mode = "mean estimation")
#' validate_query(invalid_query) # Throws error for missing modality
#' }
#' @export
validate_query <- function(query) {
  if (!is.list(query)) {
    stop(paste0("Expected `query` to be a list, but got ", class(query)))
  }

  required_keys <- c("inputs", "mode", "modality")

  missing_keys <- setdiff(required_keys, names(query))
  if (length(missing_keys) > 0) {
    stop(paste0(
      "Missing required keys in query: ", paste(missing_keys, collapse = ", "), ". ",
      "Use `get_valid_query()` to get an example."
    ))
  }

  validate_modality(query)
  validate_mode(query)

  invisible(TRUE)
}


#' @title Validate Query Modality
#' @description Validates that the modality specified in the query is allowed for the v2.0 model.
#' This function checks that the `modality` value is one of the supported modalities.
#'
#' @param query A list containing the query data.
#' @return Invisibly returns TRUE if validation passes.
#' Throws an error If the modality key is missing or if the selected modality is not allowed.
#' @examples
#' # Create a valid query
#' query <- get_valid_query()
#' validate_modality(query) # Passes validation
#'
#' # Example with invalid modality
#' \dontrun{
#' invalid_query <- get_valid_query()
#' invalid_query$modality <- "unsupported_modality"
#' validate_modality(invalid_query) # Throws error for invalid modality
#' }
#' @export
validate_modality <- function(query) {
  allowed_modalities <- unlist(MODEL_MODALITIES$"v2.0")

  modality_key <- "modality"
  if (!(modality_key %in% names(query))) {
    stop(paste0("Query requires '", modality_key, "' key."))
  }

  selected_modality <- query[[modality_key]]

  if (!(selected_modality %in% allowed_modalities)) {
    stop(paste0(
      "Invalid modality '", selected_modality, "'. ",
      "Allowed modalities: ", paste(allowed_modalities, collapse = ", ")
    ))
  }

  invisible(TRUE)
}

#' @title Validate Query Mode
#' @description Validates that the mode specified in the query is allowed for the v2.0 model.
#' This function checks that the `mode` value is one of the supported modes.
#'
#' @param query A list containing the query data.
#' @return Invisibly returns TRUE if validation passes.
#' Throws an error If the mode key is missing or if the selected mode is not allowed.
#' @examples
#' # Create a valid query
#' query <- get_valid_query()
#' validate_mode(query) # Passes validation
#'
#' # Example with invalid mode
#' \dontrun{
#' invalid_query <- get_valid_query()
#' invalid_query$mode <- "unsupported_mode"
#' validate_mode(invalid_query) # Throws error for invalid mode
#' }
#' @export
validate_mode <- function(query) {
  allowed_modes <- get_valid_modes()

  mode_key <- "mode"
  if (!(mode_key %in% names(query))) {
    stop(paste0("Query requires '", mode_key, "' key."))
  }

  selected_mode <- query[[mode_key]]

  if (!(selected_mode %in% allowed_modes)) {
    stop(paste0(
      "Invalid mode '", selected_mode, "'. ",
      "Allowed modes: ", paste(allowed_modes, collapse = ", ")
    ))
  }

  invisible(TRUE)
}
